baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'ycw Site'
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true
[params]
  avatarURL = "images/helmet.jpg"
  avatarSize = "size-xl"
  showPostsOnHomePage = "recent"
  description = "Hello, Stranger. I'm ycweng!"
  footer = "ycweng"
  accentColor = "#008080"
[menu]
  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "Paypal"
    url = "https://www.paypal.com/paypalme/ycw17"
    weight = "4"
    pre = "<span data-feather='dollar-sign'></span>"
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/ycweng"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
